sudo: required
dist: trusty
language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libhdf5-7 libhdf5-dev python3 python3-pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install hdf5 python3 python3-pip || echo "a brew error code when installing gcc is expected"; fi
  - git clone https://github.com/ComparativeGenomicsToolkit/sonLib.git
install:
  - pip install setuptools --upgrade
  - pip3 install -r requirements.txt
  - sh -c 'cd sonLib && make'
script:
  - alias python=python3
  - alias pip=pip3
  - export sonLibRootDir=`pwd`/sonLib
  - make -j 4
  - PYTHONPATH=..:.:$PYTHONPATH PATH=./bin:$PATH make -k test
os:
  - linux
  - osx
env:
  - CGL_DEBUG=1
  - CGL_DEBUG=ultra ASAN_OPTIONS=detect_leaks=0
matrix:
  exclude:
    # The default OSX env doesn't have a version that supports
    # -fsanitize=address.
    - env: CGL_DEBUG=ultra ASAN_OPTIONS=detect_leaks=0
      os: osx
